tools:
    external_code_coverage: true
filter:
  paths:
    - src/*

build:
    environment:
        php:
            version: 5.5
checks:
    php:
        code_rating: true
        duplication: true