application:
    environment:
        php:
            version: 5.3.3
filter:
  paths:
    - src/*
before_commands:
    - "composer update --prefer-source"
tools:
    php_code_coverage:
        enabled:        true
        test_command:   bin/phpunit -c app/
    external_code_coverage: true
checks:
    php:
        code_rating: true
        duplication: true