filter:
  paths:
    - src/*
before_commands:
    - "composer update --prefer-source"
php_code_coverage:
        enabled:        true
        test_command:   bin/phpunit -c app/
checks:
    php:
        code_rating: true
        duplication: true