application:
    environment:
        php:
            version: 5.3.3
project_setup:
        before:
            - phpunit --coverage-clover=coverage.clover
            - wget https://scrutinizer-ci.com/ocular.phar
            - php ocular.phar code-coverage:upload --access-token="f611b4c565158b5f7032d238777c1b22822487b154e946bef1939ecd17fc7b58" --format=php-clover coverage.clover
            - mysql -u root -e "CREATE DATABASE symfony"
            - php app/console doctrine:schema:drop --force
            - php app/console doctrine:schema:create
            - php app/console doctrine:schema:update --force
            - php app/console doctrine:fixtures:load --no-interaction
            - bin/phpunit -c app
filter:
  paths:
    - src/*
before_commands:
    - "composer update --prefer-source"
tools:
    php_code_coverage:
        enabled:        true
        test_command:   bin/phpunit -c app/
    external_code_coverage: true
checks:
    php:
        code_rating: true
        duplication: true