application:
    environment:
        php:
            version: 5.5
filter:
  excluded_paths:
  - app/*
  - src/**/DataFixtures/**/*

before_commands:
    - "composer update --prefer-source"
tools:
    external_code_coverage:
        timeout: 3600
checks:
    php:
        code_rating: true
        duplication: true