language: php

php:
    - 5.5

before_install:
    - sudo chmod 0777 -R app/logs/ app/cache/
    - mysql -e 'create database symfony;'
install:
    - composer install -n --prefer-source

script:
    - php app/console doctrine:schema:drop --force
    - php app/console doctrine:schema:create
    - php app/console doctrine:schema:update --force
    - php app/console doctrine:fixtures:load --no-interaction
    - bin/phpunit -c app
    - phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --access-token="f611b4c565158b5f7032d238777c1b22822487b154e946bef1939ecd17fc7b58" --format=php-clover coverage.clover

