zdrw_index:
    path:     /
    defaults: { _controller: ZdrwOffersBundle:Default:index }
zdrw_dares:
    path:     /dares/{page}
    defaults: { _controller: ZdrwOffersBundle:Default:dares, page: 1}
    requirements:
        page: "^\d+$"
zdrw_dare:
    path:     /dare/{id}
    defaults: { _controller: ZdrwOffersBundle:Default:dare }
zdrw_new_dare:
    path:     /new
    defaults: { _controller: ZdrwOffersBundle:Default:newDare}
zdrw_stares:
    path:     /stares/{page}
    defaults: { _controller: ZdrwOffersBundle:Default:stares, page: 1}
    requirements:
        page: "^\d+$"
zdrw_upload:
    path:     /upload
    defaults: { _controller: ZdrwOffersBundle:Video:index }
zdrw_tovimeo:
    path:     /tovimeo
    defaults: { _controller: ZdrwOffersBundle:Video:toVimeo }
zdrw_search:
    path:     /search
    defaults: { _controller: ZdrwOffersBundle:Default:search }
admin_index:
    path:     /admin
    defaults: { _controller: ZdrwOffersBundle:Admin:index }

google_url:
    pattern: /login/google
fb_url:
    pattern: /login/facebook
