zdrw_index:
    path:     /
    defaults: { _controller: ZdrwOffersBundle:Default:index }
zdrw_dares:
    path:     /dares
    defaults: { _controller: ZdrwOffersBundle:Default:dares }
zdrw_dare:
    path:     /dare/{id}
    defaults: { _controller: ZdrwOffersBundle:Default:dare }
zdrw_new_dare:
    path:     /new
    defaults: { _controller: ZdrwOffersBundle:Default:newDare}
zdrw_stares:
    path:     /stares
    defaults: { _controller: ZdrwOffersBundle:Default:stares }
zdrw_user:
    path:     /user/{name}
    defaults: { _controller: ZdrwOffersBundle:Default:user, name: admin}
zdrw_upload:
    path:     /upload
    defaults: { _controller: ZdrwOffersBundle:Video:index }
zdrw_tovimeo:
    path:     /tovimeo
    defaults: { _controller: ZdrwOffersBundle:Video:toVimeo }
zdrw_search:
    path:     /search
    defaults: { _controller: ZdrwOffersBundle:Default:search }
admin_index:
    path:     /admin
    defaults: { _controller: ZdrwOffersBundle:Admin:index }

google_url:
    pattern: /login/google
fb_url:
    pattern: /login/facebook
