zdrw_index:
    path:     /
    defaults: { _controller: ZdrwOffersBundle:Default:index }
zdrw_dares:
    path:     /dares
    defaults: { _controller: ZdrwOffersBundle:Default:dares }
zdrw_dare:
    path:     /dare/{id}
    defaults: { _controller: ZdrwOffersBundle:Default:dare, id: 0}
zdrw_new_dare:
    path:     /new
    defaults: { _controller: ZdrwOffersBundle:Default:newDare}
zdrw_stares:
    path:     /stares
    defaults: { _controller: ZdrwOffersBundle:Default:stares }
zdrw_profile:
    path:     /profile2
    defaults: { _controller: ZdrwOffersBundle:Default:profile }
zdrw_user:
    path:     /user/{name}
    defaults: { _controller: ZdrwOffersBundle:Default:user, name: admin}
zdrw_upload:
    path:     /upload
    defaults: { _controller: ZdrwOffersBundle:Video:index }
zdrw_tovimeo:
    path:     /tovimeo
    defaults: { _controller: ZdrwOffersBundle:Video:toVimeo }

homepage:
    pattern: /
google_url:
    pattern: /login/google
fb_url:
    pattern: /login/facebook
