zdrw_index:
    path:     /
    defaults: { _controller: ZdrwOffersBundle:Default:index }
zdrw_dares:
    path:     /dares
    defaults: { _controller: ZdrwOffersBundle:Default:dares }
zdrw_stares:
    path:     /stares
    defaults: { _controller: ZdrwOffersBundle:Default:stares }
zdrw_profile:
    path:     /profile
    defaults: { _controller: ZdrwOffersBundle:Default:profile }
zdrw_upload:
    path:     /upload
    defaults: { _controller: ZdrwOffersBundle:Video:index }
