main_offers:
    resource: "@MainOffersBundle/Resources/config/routing.yml"
    prefix:   /

acme_blog:
            resource: "@AcmeBlogBundle/Resources/config/routing.yml"
            prefix: /
acme_post:
            resource: "@AcmeBlogBundle/Controller/"
            type: annotation
            prefix: /