zdrw_login:
    path:     /login/
    defaults: { _controller: ZdrwUserBundle:Security:loginPage }

zdrw_profile:
    path:     /profile/
    defaults: { _controller: ZdrwUserBundle:Profile:show }

zdrw_like:
    path:     /like/{id}
    defaults: { _controller: ZdrwUserBundle:Social:like, id:1}
    requirements:
        id: "^\d+$"
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"

zdrw_comment:
    path:     /comment
    defaults: { _controller: ZdrwUserBundle:Social:comment }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"

zdrw_test:
    path:     /test
    defaults: { _controller: ZdrwUserBundle:Social:test}

zdrw_user:
    path:     /user/{name}
    defaults: { _controller: ZdrwOffersBundle:Default:user}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

google_url:
    pattern: /login/google
fb_url:
    pattern: /login/facebook