<?php

namespace Zdrw\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function countByOffer($id)
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->where('a.offer = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
