<?php

namespace Zdrw\OffersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRepository extends EntityRepository
{
}
